# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from PyQt5.uic import loadUi
import requests
from PyQt5.QtGui import QPixmap
import json
import random


class Ui_mainWindow(object):
        def setupUi(self, mainWindow):
                mainWindow.setObjectName("mainWindow")
                mainWindow.setEnabled(True)
                mainWindow.resize(980, 918)
                self.centralwidget = QtWidgets.QWidget(mainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.frame_top = QtWidgets.QFrame(self.centralwidget)
                self.frame_top.setGeometry(QtCore.QRect(70, 40, 851, 161))
                self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_top.setObjectName("frame_top")
                self.logoPicLabel = QtWidgets.QLabel(self.frame_top)
                self.logoPicLabel.setGeometry(QtCore.QRect(20, 10, 131, 131))
                font = QtGui.QFont()
                font.setPointSize(12)
                self.logoPicLabel.setFont(font)
                self.logoPicLabel.setText("")
                self.logoPicLabel.setPixmap(QtGui.QPixmap("../../Users/edwma/OneDrive/Pictures/milleniumeye.png"))
                self.logoPicLabel.setScaledContents(True)
                self.logoPicLabel.setObjectName("logoPicLabel")
                self.logoTextLabel = QtWidgets.QLabel(self.frame_top)
                self.logoTextLabel.setGeometry(QtCore.QRect(160, 30, 191, 101))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.logoTextLabel.setFont(font)
                self.logoTextLabel.setObjectName("logoTextLabel")

                self.homeButton = QtWidgets.QPushButton(self.frame_top)
                self.homeButton.setGeometry(QtCore.QRect(630, 10, 75, 23))
                self.homeButton.setStyleSheet("background-color:rgb(105,105,105);\n"
                        "color:rgb(230,230,230);\n"
                        "font-weight:bold")
                self.homeButton.setObjectName("homeButton")
                # click event for home button
                self.homeButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))

                self.browseButton = QtWidgets.QPushButton(self.frame_top)
                self.browseButton.setGeometry(QtCore.QRect(740, 10, 75, 23))
                self.browseButton.setStyleSheet("background-color:rgb(105,105,105);\n"
                        "color: rgb(230,230,230);\n"
                        "font-weight:bold")
                self.browseButton.setObjectName("browseButton")
                # click event for browse button
                self.browseButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))

                self.searchInput = QtWidgets.QLineEdit(self.frame_top)
                self.searchInput.setGeometry(QtCore.QRect(380, 90, 361, 21))
                self.searchInput.setStyleSheet("")
                self.searchInput.setText("")
                self.searchInput.setObjectName("searchInput")

                self.searchButton = QtWidgets.QPushButton(self.frame_top)
                self.searchButton.setGeometry(QtCore.QRect(740, 90, 75, 21))
                self.searchButton.setAutoFillBackground(False)
                self.searchButton.setStyleSheet("background-color:rgb(105,105,105);\n"
                        "color: rgb(230,230,230);\n"
                        "font-weight:bold")
                self.searchButton.setObjectName("searchButton")
                # click event for search button
                #self.searchButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
                self.searchButton.clicked.connect(lambda: self.search(self.searchInput.text()))

                # random card button
                self.randomButton = QtWidgets.QPushButton(self.frame_top)
                self.randomButton.setGeometry(QtCore.QRect(380, 10, 75, 23))
                self.randomButton.setStyleSheet("background-color:rgb(105,105,105);\n"
                        "color: rgb(230,230,230);\n"
                        "font-weight:bold")
                self.randomButton.setObjectName("randomButton")
                self.randomButton.clicked.connect(lambda: self.search(self.getRandomCard()))


                self.frame_pages = QtWidgets.QFrame(self.centralwidget)
                self.frame_pages.setGeometry(QtCore.QRect(69, 219, 861, 1200))
                self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_pages.setObjectName("frame_pages")
                self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
                self.stackedWidget.setGeometry(QtCore.QRect(19, 19, 821, 651))
                self.stackedWidget.setObjectName("stackedWidget")

                # home page components
                self.homePage = QtWidgets.QWidget()
                self.homePage.setObjectName("homePage")
                self.homeDetailLabel = QtWidgets.QLabel(self.homePage)
                self.homeDetailLabel.setGeometry(QtCore.QRect(10, 10, 211, 71))
                self.homeDetailLabel.setObjectName("homeDetailLabel")
                self.stackedWidget.addWidget(self.homePage)

                self.top5Label = QtWidgets.QLabel(self.homePage)
                self.top5Label.setGeometry(QtCore.QRect(300, 80, 200, 21))
                self.top5Label.setObjectName("top5Label")
                # top 10 table
                self.top5Table = QtWidgets.QTableWidget(self.homePage)
                self.top5Table.setGeometry(QtCore.QRect(10, 100, 800, 1000))
                self.top5Table.setObjectName("top5Table")


                # browse page components
                self.browsePage = QtWidgets.QWidget()
                self.browsePage.setObjectName("browsePage")
                self.browseLabel = QtWidgets.QLabel(self.browsePage)
                self.browseLabel.setGeometry(QtCore.QRect(20, 50, 61, 21))
                self.browseLabel.setObjectName("browseLabel")
                self.stackedWidget.addWidget(self.browsePage)

                self.attributeLabel = QtWidgets.QLabel(self.browsePage)
                self.attributeLabel.setGeometry(QtCore.QRect(20, 80, 61, 21))
                self.attributeLabel.setObjectName("attributeLabel")
                self.attributeLabel.setText("<b>Attributes:</b>")

                self.browseDarkButton = QtWidgets.QPushButton(self.browsePage)
                self.browseDarkButton.setGeometry(QtCore.QRect(20, 100, 60, 20))
                self.browseDarkButton.setObjectName("browseDarkButton")
                self.browseDarkButton.setText("Dark")
                self.browseDarkButton.setStyleSheet("background-color:transparent; color:blue;")

                self.browseDivineButton = QtWidgets.QPushButton(self.browsePage)
                self.browseDivineButton.setGeometry(QtCore.QRect(70, 100, 60, 20))
                self.browseDivineButton.setObjectName("browseDivineButton")
                self.browseDivineButton.setText("Divine")
                self.browseDivineButton.setStyleSheet("background-color:transparent; color:blue;")

                self.browseEarthButton = QtWidgets.QPushButton(self.browsePage)
                self.browseEarthButton.setGeometry(QtCore.QRect(120, 100, 60, 20))
                self.browseEarthButton.setObjectName("browseEarthButton")
                self.browseEarthButton.setText("Earth")
                self.browseEarthButton.setStyleSheet("background-color:transparent; color:blue;")

                self.browseFireButton = QtWidgets.QPushButton(self.browsePage)
                self.browseFireButton.setGeometry(QtCore.QRect(170, 100, 60, 20))
                self.browseFireButton.setObjectName("browseFireButton")
                self.browseFireButton.setText("Fire")
                self.browseFireButton.setStyleSheet("background-color:transparent; color:blue;")
                
                self.browseLightButton = QtWidgets.QPushButton(self.browsePage)
                self.browseLightButton.setGeometry(QtCore.QRect(220, 100, 60, 20))
                self.browseLightButton.setObjectName("browseLightButton")
                self.browseLightButton.setText("Light")
                self.browseLightButton.setStyleSheet("background-color:transparent; color:blue;")

                self.browseWaterButton = QtWidgets.QPushButton(self.browsePage)
                self.browseWaterButton.setGeometry(QtCore.QRect(270, 100, 60, 20))
                self.browseWaterButton.setObjectName("browseWaterButton")
                self.browseWaterButton.setText("Water")
                self.browseWaterButton.setStyleSheet("background-color:transparent; color:blue;")

                self.browseWindButton = QtWidgets.QPushButton(self.browsePage)
                self.browseWindButton.setGeometry(QtCore.QRect(320, 100, 60, 20))
                self.browseWindButton.setObjectName("browseWindButton")
                self.browseWindButton.setText("Wind")
                self.browseWindButton.setStyleSheet("background-color:transparent; color:blue;")

                self.browseTable = QtWidgets.QTableWidget(self.browsePage)
                self.browseTable.setGeometry(QtCore.QRect(280, 130, 300, 600))
                self.browseTable.setObjectName("browseTable")

                # search page components
                self.searchPage = QtWidgets.QWidget()
                self.searchPage.setObjectName("searchPage")
                self.searchLabel = QtWidgets.QLabel(self.searchPage)
                self.searchLabel.setGeometry(QtCore.QRect(390, 40, 51, 41))
                self.searchLabel.setObjectName("searchLabel")
                self.stackedWidget.addWidget(self.searchPage)

                self.searchPicLabel = QtWidgets.QLabel(self.searchPage)
                self.searchPicLabel.setGeometry(QtCore.QRect(0, 80, 300, 450))
                
                self.searchNameLabel = QtWidgets.QLabel(self.searchPage)
                self.searchNameLabel.setGeometry(QtCore.QRect(320, 70, 300, 40))

                self.searchDescriptionLabel = QtWidgets.QLabel(self.searchPage)
                self.searchDescriptionLabel.setGeometry(QtCore.QRect(320, 20, 400, 400))
                self.searchDescriptionLabel.setWordWrap(True)

                self.searchPriceLabel = QtWidgets.QLabel(self.searchPage)
                self.searchPriceLabel.setGeometry(QtCore.QRect(320, 500, 400, 40))

                mainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(mainWindow)
                self.stackedWidget.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(mainWindow)

        def retranslateUi(self, mainWindow):
                _translate = QtCore.QCoreApplication.translate
                mainWindow.setWindowTitle(_translate("mainWindow", "Yu-Gi-Oh! TCG Explorer"))
                self.logoTextLabel.setText(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                        "p, li { white-space: pre-wrap; }\n"
                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
                        "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Yu-Gi-Oh! </p>\n"
                        "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TCG Explorer</p></body></html>"))
                self.homeButton.setText(_translate("mainWindow", "HOME"))
                self.browseButton.setText(_translate("mainWindow", "BROWSE"))
                self.searchInput.setPlaceholderText(_translate("mainWindow", "Search Yu-Gi-Oh! Cards"))
                self.searchButton.setText(_translate("mainWindow", "SEARCH"))
                self.randomButton.setText(_translate("mainWindow", "RANDOMIZE"))
                self.homeDetailLabel.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Free Yu-Gi-Oh! TCG Lookup Tool</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Accurate card prices</span></p></body></html>"))
                self.browseLabel.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">BROWSE</span></p></body></html>"))
                self.searchLabel.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">SEARCH</span></p></body></html>"))

                self.top5Label.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Top 5 Most Expensive Cards</span></p></body></html>"))
                ###############################################################################################
                # Home components
                ###############################################################################################
                # top 10 table
                self.top5Table.setColumnCount(3)
                self.top5Table.setRowCount(5)
                self.top5Table.setColumnWidth(0, 300)
                self.top5Table.setColumnWidth(1, 400)
                self.top5Table.setColumnWidth(2, 85)
                for i in range(10):
                     self.top5Table.setRowHeight(i, 108)
                header_labels = ["", "Card", "Price"]
                self.top5Table.setHorizontalHeaderLabels(header_labels)

                for i in range(len(header_labels)):
                        header_item = self.top5Table.horizontalHeaderItem(i)
                        header_item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.populateTop5Table()

                ###############################################################################################
                # Browse components
                ###############################################################################################
                self.browseDarkButton.clicked.connect(lambda: self.populateBrowseTable('dark'))
                self.browseDivineButton.clicked.connect(lambda: self.populateBrowseTable('divine'))
                self.browseEarthButton.clicked.connect(lambda: self.populateBrowseTable('earth'))
                self.browseFireButton.clicked.connect(lambda: self.populateBrowseTable('fire'))
                self.browseLightButton.clicked.connect(lambda: self.populateBrowseTable('light'))
                self.browseWaterButton.clicked.connect(lambda: self.populateBrowseTable('water'))
                self.browseWindButton.clicked.connect(lambda: self.populateBrowseTable('wind'))

        def populateBrowseTable(self, attribute):
                
                with open(f'{attribute}Attributes.json') as f:
                        data = json.load(f)
                        if attribute == 'divine':
                                self.browseTable.setColumnCount(1)
                                self.browseTable.setRowCount(6)
                                self.browseTable.setColumnWidth(0, 300)
                                for i in range(6):
                                         self.browseTable.setRowHeight(i, 25)
                                browse_headers = ["Card Name"]
                                self.browseTable.setHorizontalHeaderLabels(browse_headers)
                                buttonName = {}
                                cardNames = {}
                                for i in range(6):
                                        card = random.choice(data['data'])
                                        while card['name'] in cardNames.values():
                                                card = random.choice(data['data'])
                                        cardNames[i] = card['name']
                                        buttonName[i] = QtWidgets.QPushButton(self.browseTable)
                                        buttonName[i].setText(card['name'])
                                        buttonName[i].clicked.connect(lambda i=i, name=card['name']: self.search(name))
                                        buttonName[i].setStyleSheet("background-color: transparent; color:blue;")
                                        self.browseTable.setCellWidget(i, 0, buttonName[i])
                        else:
                                self.browseTable.setColumnCount(1)
                                self.browseTable.setRowCount(20)
                                self.browseTable.setColumnWidth(0, 300)
                                for i in range(20):
                                         self.browseTable.setRowHeight(i, 25)
                                browse_headers = ["Card Name"]
                                self.browseTable.setHorizontalHeaderLabels(browse_headers)
                                buttonName = {}
                                cardNames = {}
                                for i in range(20):
                                        card = random.choice(data['data'])
                                        while card['name'] in cardNames.values():
                                                card = random.choice(data['data'])
                                        cardNames[i] = card['name']
                                        buttonName[i] = QtWidgets.QPushButton(self.browseTable)
                                        buttonName[i].setText(card['name'])
                                        buttonName[i].clicked.connect(lambda i=i, name=card['name']: self.search(name))
                                        buttonName[i].setStyleSheet("background-color: transparent; color:blue;")
                                        self.browseTable.setCellWidget(i, 0, buttonName[i])

        def populateTop5Table(self):
                response = requests.get('http://yugiohprices.com/api/top_100_cards')
                if response.status_code == 200:
                        data = response.json()
                        top_5_cards = data['data'][:5]
                else:
                        print('Error:', response.status_code)
                self.picLabel0 = QtWidgets.QLabel(self.top5Table)
                self.picLabel1 = QtWidgets.QLabel(self.top5Table)       
                self.picLabel2 = QtWidgets.QLabel(self.top5Table)
                self.picLabel3 = QtWidgets.QLabel(self.top5Table)
                self.picLabel4 = QtWidgets.QLabel(self.top5Table)

                self.cardLink0 = QtWidgets.QPushButton(self.top5Label)     
                self.cardLink1 = QtWidgets.QPushButton(self.top5Label)   
                self.cardLink2 = QtWidgets.QPushButton(self.top5Label)
                self.cardLink3 = QtWidgets.QPushButton(self.top5Label)
                self.cardLink4 = QtWidgets.QPushButton(self.top5Label)
                
                row = 0     
                names = [''] * 5
                for item in top_5_cards:
                        if item['name'] == 'Red Dragon Archfiend/Assault Mode':
                                item['name'] = 'Red Dragon Archfiend%2fAssault Mode'
                        if row == 0:
                                picRequest = requests.get(f'http://yugiohprices.com/api/card_image/{item["name"]}')
                                names[0] = item['name']
                                if picRequest.status_code == 200:
                                        with open('homepic1.jpg', 'wb') as f:
                                                f.write(picRequest.content)
                                else:
                                        print('Error:', picRequest.status_code)
                                pixmap = QPixmap('homepic1.jpg')
                                self.picLabel0.setPixmap(pixmap)
                                self.picLabel0.setScaledContents(True)
                                self.picLabel0.setFixedSize(80, 105)
                                self.picLabel0.setAlignment(QtCore.Qt.AlignCenter)
                                self.top5Table.setCellWidget(row, 0, self.picLabel0)

                                self.cardLink0.setText(item['name'])
                                self.cardLink0.setFixedSize(400, 30)
                                self.cardLink0.setStyleSheet("background-color: transparent; color:blue;")           
                                self.cardLink0.clicked.connect(lambda: self.search(names[0]))
                                self.top5Table.setCellWidget(row, 1, self.cardLink0)

                        elif row == 1:
                                picRequest = requests.get(f'http://yugiohprices.com/api/card_image/{item["name"]}')
                                names[1] = item['name']
                                if picRequest.status_code == 200:
                                        with open('homepic2.jpg', 'wb') as f:
                                                f.write(picRequest.content)
                                else:
                                        print('Error:', picRequest.status_code)
                                pixmap = QPixmap('homepic2.jpg')
                                self.picLabel1.setPixmap(pixmap)
                                self.picLabel1.setScaledContents(True)
                                self.picLabel1.setFixedSize(80, 105)
                                self.picLabel1.setAlignment(QtCore.Qt.AlignCenter)
                                self.top5Table.setCellWidget(row, 0, self.picLabel1)

                                # card Link
                                self.cardLink1.setText(item['name'])
                                self.cardLink1.setFixedSize(400, 30)
                                self.cardLink1.setStyleSheet("background-color: transparent; color:blue;")
                                self.top5Table.setCellWidget(row, 1, self.cardLink1)
                                self.cardLink1.clicked.connect(lambda: self.search(names[1]))

                        elif row == 2:
                                names[2] = item['name']
                                picRequest = requests.get(f'http://yugiohprices.com/api/card_image/{item["name"]}')
                                if picRequest.status_code == 200:
                                        with open('homepic3.jpg', 'wb') as f:
                                                f.write(picRequest.content)
                                else:
                                        print('Error:', picRequest.status_code)
                                pixmap = QPixmap('homepic3.jpg')
                                self.picLabel2.setPixmap(pixmap)
                                self.picLabel2.setScaledContents(True)
                                self.picLabel2.setFixedSize(80, 105)
                                self.picLabel2.setAlignment(QtCore.Qt.AlignCenter)
                                self.top5Table.setCellWidget(row, 0, self.picLabel2)

                                self.cardLink2.setText(item['name'])
                                self.cardLink2.setFixedSize(400, 30)
                                self.cardLink2.setStyleSheet("background-color: transparent; color:blue;")
                                self.top5Table.setCellWidget(row, 1, self.cardLink2)
                                self.cardLink2.clicked.connect(lambda: self.search(names[2]))

                        elif row == 3:
                                names[3] = item['name']
                                picRequest = requests.get(f'http://yugiohprices.com/api/card_image/{item["name"]}')
                                if picRequest.status_code == 200:
                                        with open('homepic4.jpg', 'wb') as f:
                                                f.write(picRequest.content)
                                else:
                                        print('Error:', picRequest.status_code)
                                pixmap = QPixmap('homepic4.jpg')
                                self.picLabel3.setPixmap(pixmap)
                                self.picLabel3.setScaledContents(True)
                                self.picLabel3.setFixedSize(80, 105)
                                self.picLabel3.setAlignment(QtCore.Qt.AlignCenter)
                                self.top5Table.setCellWidget(row, 0, self.picLabel3)

                                self.cardLink3.setText(item['name'])
                                self.cardLink3.setFixedSize(400, 30)
                                self.cardLink3.setStyleSheet("background-color: transparent; color:blue;")
                                self.top5Table.setCellWidget(row, 1, self.cardLink3)
                                self.cardLink3.clicked.connect(lambda: self.search(names[3]))

                        elif row == 4:
                                names[4] = item['name']
                                picRequest = requests.get(f'http://yugiohprices.com/api/card_image/{item["name"]}')
                                if picRequest.status_code == 200:
                                        with open('homepic5.jpg', 'wb') as f:
                                                f.write(picRequest.content)
                                else:
                                        print('Error:', picRequest.status_code)
                                pixmap = QPixmap('homepic5.jpg')
                                self.picLabel4.setPixmap(pixmap)
                                self.picLabel4.setScaledContents(True)
                                self.picLabel4.setFixedSize(80, 105)
                                self.picLabel4.setAlignment(QtCore.Qt.AlignCenter)
                                self.top5Table.setCellWidget(row, 0, self.picLabel4)

                                self.cardLink4.setText(item['name'])
                                self.cardLink4.setFixedSize(400, 30)
                                self.cardLink4.setStyleSheet("background-color: transparent; color:blue")
                                self.top5Table.setCellWidget(row, 1, self.cardLink4)
                                self.cardLink4.clicked.connect(lambda: self.search(names[4]))

                        #self.top5Table.setItem(row, 1, QTableWidgetItem(item['name']))
                        self.top5Table.setItem(row, 2, QTableWidgetItem(str(item['price'])))
                        # Set the item flags to make the cells not editable
                        #self.top5Table.item(row, 1).setFlags(QtCore.Qt.ItemIsEnabled)
                        self.top5Table.item(row, 2).setFlags(QtCore.Qt.ItemIsEnabled)
                        row += 1

        def search(self, name):
                self.stackedWidget.setCurrentIndex(2)
                #print(self.searchInput.text())
                #self.searchPicLabel.setText(self.searchInput.text())
                picRequest = requests.get(f'http://yugiohprices.com/api/card_image/{name}')
                try:
                        if picRequest.status_code == 200:
                                with open('searchpic.jpg', 'wb') as f:
                                        f.write(picRequest.content)
                                pixmap = QPixmap('searchpic.jpg')
                                self.searchPicLabel.setPixmap(pixmap)
                                self.searchPicLabel.setScaledContents(True)
                except:
                        self.searchPicLabel.setText("Unavailable Image")
                        print('Error:', picRequest.status_code)
                        

                cardRequest = requests.get(f'http://yugiohprices.com/api/card_data/{name}')
                try:
                        if cardRequest.status_code == 200:
                                data = cardRequest.json()
                                card_name = data['data']['name']
                                self.searchNameLabel.setText(f"<b>Name:</b>\n\n{card_name}")

                                card_description = data['data']['text']
                                self.searchDescriptionLabel.setText(card_description)

                except:
                        self.searchNameLabel.setText("Cannot find card")
                        self.searchDescriptionLabel.setText("Please search for a valid card name")
                        print('Error:', cardRequest.status_code)
                        
                priceRequest = requests.get(f'http://yugiohprices.com/api/get_card_prices/{name}')
                try:
                        if priceRequest.status_code == 200:
                                data = priceRequest.json()
                                card_price = data['data'][0]['price_data']['data']['prices']
                                self.searchPriceLabel.setText(f"<b>Price:</b> High:{card_price['high']}     Low:{card_price['low']}     Average:{card_price['average']}")
                except:
                        self.searchPriceLabel.setText("Cannot find card")
                        print('Error:', priceRequest.status_code)

        def getRandomCard(self):
                print('Random button clicked: Getting random card')
                response = requests.get("https://cs361-microservice.onrender.com/yugioh")
                if response.status_code == 200:
                        data = response.json()
                        name = data['name']
                        print(name)
                        return name
                else:
                        print('Error:', response.status_code)


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        mainWindow = QtWidgets.QMainWindow()
        ui = Ui_mainWindow()
        ui.setupUi(mainWindow)
        mainWindow.show()
        sys.exit(app.exec_())
